name: 'Project Card Release Automation'
description: 'Automate semantic versioning using Github project cards.'
inputs:
  command:
    description: 'The command to run (trigger-release, initialize-card, or validate-version)'
    required: true
  releaseType:
    description: 'For initialize-card, the semantic version release type (major, minor, or patch)'
  newVersion:
    description: 'For validate-version, the new version to update to'
runs:
  using: 'node12'
  main: 'dist/index.js'
