# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Lint"
    key: "lint"
    plugins: [$CI_TOOLKIT]
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew lintRelease ciktlint
    artifact_paths:
      - "**/build/reports/lint-results.*"
      - "**/build/ktlint.xml"

  - label: "Test"
    key: "test"
    plugins: [$CI_TOOLKIT]
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew test

  - label: "Publish {{matrix}} to S3"
    depends_on:
      - "lint"
      - "test"
    plugins: [$CI_TOOLKIT]
    matrix:
      - AutomatticTracks
      - experimentation
      - crashlogging
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew \
          :{{matrix}}:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :{{matrix}}:publish
