name: 'Project Card Release Automation'
description: 'Automate semantic versioning using Github project cards.'
inputs:
  workflowId:
    required: true
    description: 'The file name of the workflow to run.'
  token:
    required: true
    description: 'Github token to use to trigger the release. (This must be a different token than the default github-actions token.)'
runs:
  using: 'node12'
  main: 'dist/index.js'
