name: Cron check links in OpenAPI spec

on:
  schedule:
    - cron: "0 0 * * 0" # Once a week on Sunday

jobs:
  linkChecker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress api-example.yaml

      # - name: Create Issue From File
      #   if: steps.lychee.outputs.exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
      #     assignees: svx