name: Release

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: goreleaser
      uses: docker://goreleaser/goreleaser:v0.104
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
