name: Build and release docker images

on:
  release:
    types:
      - created

jobs:
  build_docker:
    name: Build docker image release
    runs-on: ubuntu-latest
    env:
      GHZ_VERSION: "0.95.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: hellofreshtech
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker base image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            GHZ_VERSION=${{env.GHZ_VERSION}}
          tags: |
            hellofresh/kangal-ghz:${{env.GHZ_VERSION}}
            hellofresh/kangal-ghz:latest
