name: "Testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_EXCLUDE: .*testdata/.*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          DEFAULT_BRANCH: master

  test:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: hellofresh/kangal-ghz:local
          push: false

      - name: Build Test Server
        run: |
          cd testdata
          go mod vendor
          go build -o greeter_server greeter_server/main.go

      - name: Test
        run: |
          ./testdata/greeter_server/main &
          docker run --rm -v `pwd`:/app -w /app \
          --add-host=host.docker.internal:host-gateway \
          hellofresh/kangal-ghz:local \
          --insecure \
          --async \
          --proto testdata/helloworld/helloworld.proto \
          --call helloworld.Greeter/SayHello \
          -n 10 \
          -d '{"name":"{{.WorkerID}}"}' \
          host.docker.internal:50051
          kill $!

      - name: Test reflection
        run: |
          ./testdata/greeter_server/main --enable-reflection &
          docker run --rm -v `pwd`:/app -w /app \
          --add-host=host.docker.internal:host-gateway \
          hellofresh/kangal-ghz:local \
          --insecure \
          --async \
          --call helloworld.Greeter/SayHello \
          -n 10 \
          -d '{"name":"{{.WorkerID}}"}' \
          host.docker.internal:50051
